=== candoumbe/MiscUtilities/.nuke/build.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/build",
  "title": "Build Schema",
  "definitions": {
    "build": {
      "type": "object",
      "properties": {
        "AutoStash": {
          "type": "boolean",
          "description": "Indicates if any changes should be stashed automatically prior to switching branch (Default : true)"
        },
        "CodecovToken": {
          "type": "string",
          "description": "The API key used to push code coverage to CodeCov",
          "default": "Secrets must be entered via 'nuke :secrets [profile]'"
        },
        "ConfigName": {
          "type": "string",
          "description": "Defines the name of the configuration to use to publish packages"
        },
        "Configuration": {
          "type": "string",
          "description": "Defines the configuratoin to use when building the application",
          "enum": [
            "Debug",
            "Release"
          ]
        },
        "Continue": {
          "type": "boolean",
          "description": "Indicates to continue a previously failed build attempt"
        },
        "DeleteLocalOnSuccess": {
          "type": "boolean",
          "description": "Should the local branch be deleted after the pull request was created successfully ?"
        },
        "Description": {
          "type": "string",
          "description": "Description of the pull request"
        },
        "Draft": {
          "type": "boolean",
          "description": "Indicates to open the pull request as 'draft'"
        },
        "GitHubToken": {
          "type": "string",
          "description": "Token used to create a new release in GitHub",
          "default": "Secrets must be entered via 'nuke :secrets [profile]'"
        },
        "Help": {
          "type": "boolean",
          "description": "Shows the help text for this build assembly"
        },
        "Host": {
          "type": "string",
          "description": "Host for execution. Default is 'automatic'",
          "enum": [
            "AppVeyor",
            "AzurePipelines",
            "Bamboo",
            "Bitbucket",
            "Bitrise",
            "GitHubActions",
            "GitLab",
            "Jenkins",
            "Rider",
            "SpaceAutomation",
            "TeamCity",
            "Terminal",
            "TravisCI",
            "VisualStudio",
            "VSCode"
          ]
        },
        "IgnoreFailedSources": {
          "type": "boolean",
          "description": "Ignore unreachable sources during Restore"
        },
        "Issues": {
          "type": "array",
          "description": "Issues that will be closed once the pull request is completed",
          "items": {
            "type": "string"
          }
        },
        "Major": {
          "type": "boolean",
          "description": "Hint to create a major release"
        },
        "Name": {
          "type": "string",
          "description": "Name of the branch to create"
        },
        "NoLogo": {
          "type": "boolean",
          "description": "Disables displaying the NUKE logo"
        },
        "NugetApiKey": {
          "type": "string",
          "description": "Token to interact with Nuget's API",
          "default": "Secrets must be entered via 'nuke :secrets [profile]'"
        },
        "Partition": {
          "type": "string",
          "description": "Partition to use on CI"
        },
        "Plan": {
          "type": "boolean",
          "description": "Shows the execution plan (HTML)"
        },
        "Profile": {
          "type": "string",
          "description": "Name of the profile where the current set of secrets"
        },
        "Root": {
          "type": "string",
          "description": "Root directory during build execution"
        },
        "Skip": {
          "type": "array",
          "description": "List of targets to be skipped. Empty list skips all dependencies",
          "items": {
            "type": "string",
            "enum": [
              "AddGithubRelease",
              "Benchmarks",
              "Changelog",
              "Clean",
              "Coldfix",
              "Compile",
              "Feature",
              "Hotfix",
              "ManageSecrets",
              "MutationTests",
              "Pack",
              "Publish",
              "Release",
              "ReportCoverage",
              "Restore",
              "Tests",
              "UnitTests"
            ]
          }
        },
        "Solution": {
          "type": "string",
          "description": "Path to a solution file that is automatically loaded"
        },
        "StrykerDashboardApiKey": {
          "type": "string",
          "description": "API KEY used to submit mutation report to a stryker dashboard",
          "default": "Secrets must be entered via 'nuke :secrets [profile]'"
        },
        "Target": {
          "type": "array",
          "description": "List of targets to be invoked. Default is '{default_target}'",
          "items": {
            "type": "string",
            "enum": [
              "AddGithubRelease",
              "Benchmarks",
              "Changelog",
              "Clean",
              "Coldfix",
              "Compile",
              "Feature",
              "Hotfix",
              "ManageSecrets",
              "MutationTests",
              "Pack",
              "Publish",
              "Release",
              "ReportCoverage",
              "Restore",
              "Tests",
              "UnitTests"
            ]
          }
        },
        "Title": {
          "type": "string",
          "description": "Title that will be used when creating a PR"
        },
        "Verbosity": {
          "type": "string",
          "description": "Logging verbosity during build execution. Default is 'Normal'",
          "enum": [
            "Minimal",
            "Normal",
            "Quiet",
            "Verbose"
          ]
        }
      }
    }
  }
}

=== candoumbe/MiscUtilities/.nuke/parameters.local.json
{
  "GitHubToken": "v1:g7QbfzIRqw0wemYuaIn3QZLb1OR7q4XNf/HFC4GDaFk9Dj2xC2VO88Ec0OgwFxADpnYOCMN5RTC5TQuZs7ytZIbyQlnyYBIJKDYJm8XTnT+i922kH1wVsyLXTamSqH2N",
  "NugetApiKey": "v1:H5CochuORkSZe9/pd40sI9LEAGn22zu1Yl1rOhzmwJ5u9C71fvO5tOOIA7job0Xx",
  "StrykerDashboardApiKey": "v1:q92/VgrQddy+31gja/B405ylZGdcP/Fjk7cC4BKGP4aZL3O1ruz6WMZ8IEDsNDnF",
  "CodecovToken": "v1:MjS3MNQqwWIQHBYIxjtQ5l1b3e8Z3IuzhLJLQwQduz9J1jtsW9yCbwdihryK0tx1"
}
